const SUPABASE_URL="https://odusqcievoipwrtnsftz.supabase.co",KEY="sb_publishable_03VYlZENfp-OxRuyZvDe9g_tKS5ztDx",db=supabase.createClient(SUPABASE_URL,KEY);
const $=s=>document.querySelector(s),esc=s=>String(s||"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
const cols=[["inbox","Входящие","#94a3b8"],["progress","В работе","#0ea5e9"],["waiting","На контроле","#f59e0b"],["done","Сделано","#10b981"]];
let tasks=[],comments=[],visibleTasks=[],current=null;
const fmt=x=>new Date(x).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}),dateOnly=x=>x?String(x).slice(0,10):"";
function showAuth(){$("#auth-view").hidden=false;$("#app-view").hidden=true}
async function showApp(){$("#auth-view").hidden=true;$("#app-view").hidden=false;await load()}
async function boot(){try{const {data,error}=await db.auth.getSession();if(error)throw error;data.session?await showApp():showAuth()}catch(error){$("#auth-message").textContent="Не удалось подключиться: "+error.message;showAuth()}}
async function load(){const [a,b]=await Promise.all([db.from("tasks").select("*").order("updated_at",{ascending:false}),db.from("task_comments").select("*").order("created_at",{ascending:false})]);if(a.error||b.error){$("#load-error").hidden=false;$("#load-error").textContent="Не удалось загрузить задачи.";return}$("#load-error").hidden=true;tasks=a.data||[];comments=b.data||[];render()}
function render(){const f={q:$("#search").value.toLowerCase(),cat:$("#category-filter").value,st:$("#status-filter").value,cf:$("#created-from").value,ct:$("#created-to").value,df:$("#completed-from").value,dt:$("#completed-to").value};visibleTasks=tasks.filter(t=>{const text=(t.title+" "+t.description+" "+(t.tags||[]).join(" ")).toLowerCase(),created=dateOnly(t.created_at),completed=dateOnly(t.completed_at);return(!f.cat||t.category===f.cat)&&(!f.st||t.status===f.st)&&text.includes(f.q)&&(!f.cf||created>=f.cf)&&(!f.ct||created<=f.ct)&&(!f.df||completed>=f.df)&&(!f.dt||completed<=f.dt)});$("#board").innerHTML=cols.map(c=>{const list=visibleTasks.filter(t=>t.status===c[0]);return '<section class="column"><div class="column-head"><span><i style="background:'+c[2]+'"></i>'+c[1]+'<em class="count">'+list.length+'</em></span><button class="add-small" data-new="'+c[0]+'">＋</button></div><div class="cards">'+list.map(card).join("")+(!list.length?'<button class="card" data-new="'+c[0]+'" style="color:#8994a6;text-align:center;border-style:dashed">Добавить задачу</button>':"")+"</div></section>"}).join("");document.querySelectorAll("[data-task]").forEach(x=>x.onclick=()=>openTask(x.dataset.task));document.querySelectorAll("[data-new]").forEach(x=>x.onclick=()=>openTask(null,x.dataset.new))}
function card(t){const n=comments.filter(c=>c.task_id===t.id).length,due=t.due_date?new Date(t.due_date+"T00:00:00").toLocaleDateString("ru-RU",{day:"2-digit",month:"short"}):"",late=t.due_date&&new Date(t.due_date+"T00:00:00")<new Date(new Date().toDateString());return '<button class="card" data-task="'+t.id+'"><div class="card-title">'+esc(t.title)+' <i class="dot '+t.category+'"></i></div><div class="tags">'+(t.tags||[]).slice(0,3).map(x=>'<span class="tag">#'+esc(x)+"</span>").join("")+'</div><div class="card-bottom"><span class="'+(late?"late":"")+'">'+(due?"◷ "+due:"")+"</span><span>"+(n?"▢ "+n:"")+"</span></div></button>"}
function openTask(id,status){current=id?tasks.find(x=>x.id===id):null;$("#dialog-title").textContent=current?"Карточка задачи":"Новая задача";$("#task-title").value=current?.title||"";$("#task-description").value=current?.description||"";$("#task-status").value=current?.status||status||"inbox";$("#task-category").value=current?.category||"work";$("#task-due").value=current?.due_date||"";$("#task-tags").value=(current?.tags||[]).join(", ");$("#activity").hidden=!current;$("#delete-task").hidden=!current;$("#comments").innerHTML=current?(comments.filter(x=>x.task_id===current.id).map(x=>'<div class="comment">'+esc(x.body)+"<time>"+fmt(x.created_at)+"</time></div>").join("")||"<p class='muted'>Пока нет комментариев.</p>"):"";$("#task-dialog").showModal()}
$("#task-form").onsubmit=async e=>{e.preventDefault();const next=$("#task-status").value,x={title:$("#task-title").value.trim(),description:$("#task-description").value.trim(),status:next,category:$("#task-category").value,due_date:$("#task-due").value||null,tags:$("#task-tags").value.split(",").map(x=>x.trim().replace(/^#/,"")).filter(Boolean),updated_at:new Date().toISOString()};if(!x.title)return;if(next==="done"&&current?.status!=="done")x.completed_at=new Date().toISOString();if(next!=="done")x.completed_at=null;const r=current?await db.from("tasks").update(x).eq("id",current.id):await db.from("tasks").insert(x);if(r.error)return alert("Не удалось сохранить задачу.");$("#task-dialog").close();load()};
$("#add-comment").onclick=async()=>{const body=$("#comment-input").value.trim();if(!body||!current)return;const r=await db.from("task_comments").insert({task_id:current.id,body});if(r.error)return alert("Не удалось добавить комментарий.");await db.from("tasks").update({updated_at:new Date().toISOString()}).eq("id",current.id);$("#comment-input").value="";await load();openTask(current.id)};
$("#delete-task").onclick=async()=>{if(current&&confirm("Удалить задачу вместе с комментариями?")){await db.from("tasks").delete().eq("id",current.id);$("#task-dialog").close();load()}};
$("#new-task").onclick=()=>openTask();["#search","#category-filter","#status-filter","#created-from","#created-to","#completed-from","#completed-to"].forEach(s=>{$(s).oninput=render;$(s).onchange=render});
$("#auth-form").onsubmit=async e=>{e.preventDefault();const msg=$("#auth-message"),button=e.submitter;msg.textContent="Проверяю вход…";button.disabled=true;try{const {data,error}=await db.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error)throw error;if(!data.session)throw new Error("Сессия не создана");msg.textContent="";await showApp()}catch(error){msg.textContent="Ошибка входа: "+error.message}finally{button.disabled=false}};
$("#signup").onclick=async()=>{const msg=$("#auth-message");msg.textContent="Создаю аккаунт…";try{const {data,error}=await db.auth.signUp({email:$("#email").value.trim(),password:$("#password").value,options:{emailRedirectTo:"https://m4352504.github.io/my_plan/"}});if(error)throw error;if(data.session){msg.textContent="";return showApp()}msg.textContent="Аккаунт создан. Подтверди почту по ссылке из письма, затем войди."}catch(error){msg.textContent="Ошибка регистрации: "+error.message}};
$("#logout").onclick=async()=>{await db.auth.signOut();showAuth()};
$("#export").onclick=()=>{const rows=visibleTasks.filter(t=>t.status==="done").map(t=>[t.title,{work:"Работа",personal:"Личное",home:"Дом"}[t.category],dateOnly(t.created_at),dateOnly(t.completed_at),t.due_date||"",comments.filter(c=>c.task_id===t.id).map(c=>fmt(c.created_at)+" — "+c.body).join(" | ")]),csv=["Задача;Категория;Дата создания;Дата завершения;Дедлайн;Комментарии"].concat(rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(";"))).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="выполненные-задачи.csv";a.click()};
boot();
